name: Push Trigger Workflow

on:
  push:
    branches: 
      - '*'
  workflow_call:

jobs:
  run-on-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: echo "This workflow was triggered by a push"
  