name: Push Trigger Workflow

on:
  push:
    branches: 
      - '*'
  workflow_call:

jobs:
  run-on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.DEPLOYMENT_BRANCH }}
      
      - name: Print Message
        run: echo "This workflow was triggered by a push"
